### ISSUE TITLE
Improper CRS used in point-cloud.json example

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/coverage-implementation-schema#13]
The [point cloud example](https://github.com/opengeospatial/coverage-implementation-schema/blob/main/standard/schemas/1.1/json/examples/point-cloud.json) currently uses http://www.opengis.net/def/crs/EPSG/0/4979.

That CRS uses `Lat`, `Lon`, `h` (above WGS84 ellipsoid).
The example names the axes `x`,`y` and `h` and uses meters values for `x` & `y`.

http://www.opengis.net/def/crs/EPSG/0/4978 is ECEF with `x`, `y`, `z`, but then none of these coordinates is _height_ (z is from center of the Earth away towards the North pole).

Possibly we could use a CRS like http://www.opengis.net/def/crs/EPSG/0/5555 (UTM Zone 32N + height), but in this case the axis abbreviation would be `E`, `N` and `H`.

**Comment by pebau** [comment]
@jerstlouis @kathischleidt looking up  http://www.opengis.net/def/crs/EPSG/0/4979 I find "Ellipsoidal 3D CS. Axes: latitude, longitude, ellipsoidal height. Orientations: north, east, up. UoM: degree, degree, metre". So h correlates with height. So I see no reason for change here. 

Conversely, there is enough work to be done elsewhere:
- if we want to work in this domain, why not create a bathymetry example? Might be interesting to have nonnegative depth values (reversed axis direction).
- Also, clarifying MSL in our context might be helpful to many.
- Finally, talking about vertical axes: we still have no CRS for pressure proxies in hPa, and I am totally unclear about possible transformations there.

**Comment by pebau** [comment]
ah, sorry, I see now that the concern might rather be about the uom: m vs deg. That might be a candidate for a fix indeed.

**Comment by jerstlouis** [comment]
@pebau Correct, the concern is with 4979 it should be Lat & Lon in degrees, not x and y in Meters.
And if it were 4978, then all x,y and z should be Meters away from the center of the Earth (not from the ellipsoid surface).
As I said the values might make sense for 5555 or some other UTM zone + height, but the axes in that case should be renamed E, N, H.

I'm all for adding examples that clarify additional use cases, but wrong examples are worst than no example at all as implementers will be misguided.

**Comment by jerstlouis** [comment]
This issue was fixed by 5c45190815f1c2c63665eb37a9c860d0cb34898d
